# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "jiko"
license = "MIT"
licenselink = "https://github.com/skwee357/jiko/blob/master/LICENSE"
description = "A versatile, minimalist, fast and clean hugo theme inspired by Dawn and Edition themes from Ghost Blogging Platform"
tags = ["clean", "minimalist", "fast", "versatile"]
features = ["dark", "light", "multilingual", "featured image", "web mentions"]
min_version = "0.41.0"

[author]
  name = "Dmitry Kudryavtsev"
  homepage = "https://yieldcode.blog"

# If porting an existing theme
[original]
  name = "Ghost Foundation"
  homepage = "https://ghost.org/"
  repo = "https://github.com/TryGhost/Ghost"
